---
- name: Install high availability load-balancers solution for Kubernetes'master
  hosts: k8s-loadbalancers
  tasks:
  - name: Download dependencies
    local_action:
     command ansible-galaxy install -r requirements.yml  --roles-path roles --force
  
  - name: Install load-balancer for Kubernetes
    include_role:
      name: install-ha-proxy
  
  - name: Install keepalived for kubernetes
    include_role:
      name: install-keepalived
...