---
- name: Install load-balancer for Kubernetes
  hosts: k8s-loadbalancers
  roles:
  - install-ha-proxy
  
- name: Install keepalived for kubernetes
  hosts: k8s-loadbalancers
  roles:
  - install-keepalived
...