---
roles:
- name: install-ha-proxy
  src: git@github.com:BenjaminConotte/install-ha-proxy.git
  type: git
  version: main

- name: install-keepalived
  src: git@github.com:BenjaminConotte/install-keepalived.git
  type: git
  version: main
...