- name: Update repositories on Ubuntu
  become: yes
  apt:
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install HA Proxy on Ubuntu
  become: yes
  apt:
    name: haproxy
    state: present
  when: ansible_distribution == 'Ubuntu'
