- name: Update repositories on Ubuntu
  become: yes
  apt:
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install HA Proxy on Ubuntu
  become: yes
  apt:
    name: haproxy
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Configure HA Proxy on Ubuntu
  become: yes
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy
  when: ansible_distribution == 'Ubuntu'
  notify:
  - Restart HA Proxy service