- name: Update repositories on Ubuntu
  become: yes
  apt:
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install HA Proxy on Ubuntu
  become: yes
  apt:
    name: haproxy
    state: present
  when: ansible_distribution == 'Ubuntu'
- name: debug variable
  debug:
    var: hostvars['192.168.96.10']
- name: Configure HA Proxy on Ubuntu
  become: yes
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  when: ansible_distribution == 'Ubuntu'
  notify:
  - Restart HA Proxy svc